---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
# https://yamllint.readthedocs.io/en/stable/configuration.html#configuration
extends: default
rules:
    braces:
        max-spaces-inside: 1
    new-lines:
        level: warning
        type: unix
    line-length: disable
    truthy: disable
    comments: disable
    document-start: disable
