/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsYamlValidatorRouteImport } from './routes/tools/yaml-validator'
import { Route as ToolsXmlJsonRouteImport } from './routes/tools/xml-json'
import { Route as ToolsValidatorRouteImport } from './routes/tools/validator'
import { Route as ToolsUuidRouteImport } from './routes/tools/uuid'
import { Route as ToolsUserAgentParserRouteImport } from './routes/tools/user-agent-parser'
import { Route as ToolsUrlParserRouteImport } from './routes/tools/url-parser'
import { Route as ToolsUrlEncodeRouteImport } from './routes/tools/url-encode'
import { Route as ToolsUnitConverterRouteImport } from './routes/tools/unit-converter'
import { Route as ToolsTotpRouteImport } from './routes/tools/totp'
import { Route as ToolsTimestampRouteImport } from './routes/tools/timestamp'
import { Route as ToolsTextToolsRouteImport } from './routes/tools/text-tools'
import { Route as ToolsStringCounterRouteImport } from './routes/tools/string-counter'
import { Route as ToolsSqlFormatterRouteImport } from './routes/tools/sql-formatter'
import { Route as ToolsSlugGeneratorRouteImport } from './routes/tools/slug-generator'
import { Route as ToolsRegexTesterRouteImport } from './routes/tools/regex-tester'
import { Route as ToolsRandomDataRouteImport } from './routes/tools/random-data'
import { Route as ToolsQrScannerRouteImport } from './routes/tools/qr-scanner'
import { Route as ToolsQrCodeRouteImport } from './routes/tools/qr-code'
import { Route as ToolsPasswordGeneratorRouteImport } from './routes/tools/password-generator'
import { Route as ToolsNumberBaseRouteImport } from './routes/tools/number-base'
import { Route as ToolsMorseCodeRouteImport } from './routes/tools/morse-code'
import { Route as ToolsMockDataRouteImport } from './routes/tools/mock-data'
import { Route as ToolsMarkdownPreviewRouteImport } from './routes/tools/markdown-preview'
import { Route as ToolsLoremIpsumRouteImport } from './routes/tools/lorem-ipsum'
import { Route as ToolsJwtGeneratorRouteImport } from './routes/tools/jwt-generator'
import { Route as ToolsJwtDecoderRouteImport } from './routes/tools/jwt-decoder'
import { Route as ToolsJsonYamlRouteImport } from './routes/tools/json-yaml'
import { Route as ToolsJsonValidatorRouteImport } from './routes/tools/json-validator'
import { Route as ToolsJsonToTypescriptRouteImport } from './routes/tools/json-to-typescript'
import { Route as ToolsJsonFormatterRouteImport } from './routes/tools/json-formatter'
import { Route as ToolsJsonDiffRouteImport } from './routes/tools/json-diff'
import { Route as ToolsIpSubnetRouteImport } from './routes/tools/ip-subnet'
import { Route as ToolsImageToBase64RouteImport } from './routes/tools/image-to-base64'
import { Route as ToolsHttpStatusRouteImport } from './routes/tools/http-status'
import { Route as ToolsHtmlFormatterRouteImport } from './routes/tools/html-formatter'
import { Route as ToolsHtmlEntityRouteImport } from './routes/tools/html-entity'
import { Route as ToolsHmacRouteImport } from './routes/tools/hmac'
import { Route as ToolsHashRouteImport } from './routes/tools/hash'
import { Route as ToolsDiffCheckerRouteImport } from './routes/tools/diff-checker'
import { Route as ToolsDiffRouteImport } from './routes/tools/diff'
import { Route as ToolsDataUriRouteImport } from './routes/tools/data-uri'
import { Route as ToolsCsvJsonRouteImport } from './routes/tools/csv-json'
import { Route as ToolsCssMinifierRouteImport } from './routes/tools/css-minifier'
import { Route as ToolsCronParserRouteImport } from './routes/tools/cron-parser'
import { Route as ToolsCronBuilderRouteImport } from './routes/tools/cron-builder'
import { Route as ToolsColorPaletteRouteImport } from './routes/tools/color-palette'
import { Route as ToolsColorConverterRouteImport } from './routes/tools/color-converter'
import { Route as ToolsCipherRouteImport } from './routes/tools/cipher'
import { Route as ToolsCaseConverterRouteImport } from './routes/tools/case-converter'
import { Route as ToolsBase64ImageRouteImport } from './routes/tools/base64-image'
import { Route as ToolsBase64RouteImport } from './routes/tools/base64'
import { Route as ToolsBaseConversionRouteImport } from './routes/tools/base-conversion'
import { Route as ToolsBackslashEscapeRouteImport } from './routes/tools/backslash-escape'
import { Route as ToolsAsciiArtRouteImport } from './routes/tools/ascii-art'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsYamlValidatorRoute = ToolsYamlValidatorRouteImport.update({
  id: '/yaml-validator',
  path: '/yaml-validator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsXmlJsonRoute = ToolsXmlJsonRouteImport.update({
  id: '/xml-json',
  path: '/xml-json',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsValidatorRoute = ToolsValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsUuidRoute = ToolsUuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsUserAgentParserRoute = ToolsUserAgentParserRouteImport.update({
  id: '/user-agent-parser',
  path: '/user-agent-parser',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsUrlParserRoute = ToolsUrlParserRouteImport.update({
  id: '/url-parser',
  path: '/url-parser',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsUrlEncodeRoute = ToolsUrlEncodeRouteImport.update({
  id: '/url-encode',
  path: '/url-encode',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsUnitConverterRoute = ToolsUnitConverterRouteImport.update({
  id: '/unit-converter',
  path: '/unit-converter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTotpRoute = ToolsTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTimestampRoute = ToolsTimestampRouteImport.update({
  id: '/timestamp',
  path: '/timestamp',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTextToolsRoute = ToolsTextToolsRouteImport.update({
  id: '/text-tools',
  path: '/text-tools',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsStringCounterRoute = ToolsStringCounterRouteImport.update({
  id: '/string-counter',
  path: '/string-counter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSqlFormatterRoute = ToolsSqlFormatterRouteImport.update({
  id: '/sql-formatter',
  path: '/sql-formatter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSlugGeneratorRoute = ToolsSlugGeneratorRouteImport.update({
  id: '/slug-generator',
  path: '/slug-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRegexTesterRoute = ToolsRegexTesterRouteImport.update({
  id: '/regex-tester',
  path: '/regex-tester',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRandomDataRoute = ToolsRandomDataRouteImport.update({
  id: '/random-data',
  path: '/random-data',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsQrScannerRoute = ToolsQrScannerRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsQrCodeRoute = ToolsQrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPasswordGeneratorRoute = ToolsPasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsNumberBaseRoute = ToolsNumberBaseRouteImport.update({
  id: '/number-base',
  path: '/number-base',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMorseCodeRoute = ToolsMorseCodeRouteImport.update({
  id: '/morse-code',
  path: '/morse-code',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMockDataRoute = ToolsMockDataRouteImport.update({
  id: '/mock-data',
  path: '/mock-data',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMarkdownPreviewRoute = ToolsMarkdownPreviewRouteImport.update({
  id: '/markdown-preview',
  path: '/markdown-preview',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsLoremIpsumRoute = ToolsLoremIpsumRouteImport.update({
  id: '/lorem-ipsum',
  path: '/lorem-ipsum',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJwtGeneratorRoute = ToolsJwtGeneratorRouteImport.update({
  id: '/jwt-generator',
  path: '/jwt-generator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJwtDecoderRoute = ToolsJwtDecoderRouteImport.update({
  id: '/jwt-decoder',
  path: '/jwt-decoder',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJsonYamlRoute = ToolsJsonYamlRouteImport.update({
  id: '/json-yaml',
  path: '/json-yaml',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJsonValidatorRoute = ToolsJsonValidatorRouteImport.update({
  id: '/json-validator',
  path: '/json-validator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJsonToTypescriptRoute = ToolsJsonToTypescriptRouteImport.update({
  id: '/json-to-typescript',
  path: '/json-to-typescript',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJsonFormatterRoute = ToolsJsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsJsonDiffRoute = ToolsJsonDiffRouteImport.update({
  id: '/json-diff',
  path: '/json-diff',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsIpSubnetRoute = ToolsIpSubnetRouteImport.update({
  id: '/ip-subnet',
  path: '/ip-subnet',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImageToBase64Route = ToolsImageToBase64RouteImport.update({
  id: '/image-to-base64',
  path: '/image-to-base64',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHttpStatusRoute = ToolsHttpStatusRouteImport.update({
  id: '/http-status',
  path: '/http-status',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHtmlFormatterRoute = ToolsHtmlFormatterRouteImport.update({
  id: '/html-formatter',
  path: '/html-formatter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHtmlEntityRoute = ToolsHtmlEntityRouteImport.update({
  id: '/html-entity',
  path: '/html-entity',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHmacRoute = ToolsHmacRouteImport.update({
  id: '/hmac',
  path: '/hmac',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsHashRoute = ToolsHashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDiffCheckerRoute = ToolsDiffCheckerRouteImport.update({
  id: '/diff-checker',
  path: '/diff-checker',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDiffRoute = ToolsDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDataUriRoute = ToolsDataUriRouteImport.update({
  id: '/data-uri',
  path: '/data-uri',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCsvJsonRoute = ToolsCsvJsonRouteImport.update({
  id: '/csv-json',
  path: '/csv-json',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCssMinifierRoute = ToolsCssMinifierRouteImport.update({
  id: '/css-minifier',
  path: '/css-minifier',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCronParserRoute = ToolsCronParserRouteImport.update({
  id: '/cron-parser',
  path: '/cron-parser',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCronBuilderRoute = ToolsCronBuilderRouteImport.update({
  id: '/cron-builder',
  path: '/cron-builder',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsColorPaletteRoute = ToolsColorPaletteRouteImport.update({
  id: '/color-palette',
  path: '/color-palette',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsColorConverterRoute = ToolsColorConverterRouteImport.update({
  id: '/color-converter',
  path: '/color-converter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCipherRoute = ToolsCipherRouteImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCaseConverterRoute = ToolsCaseConverterRouteImport.update({
  id: '/case-converter',
  path: '/case-converter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBase64ImageRoute = ToolsBase64ImageRouteImport.update({
  id: '/base64-image',
  path: '/base64-image',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBaseConversionRoute = ToolsBaseConversionRouteImport.update({
  id: '/base-conversion',
  path: '/base-conversion',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBackslashEscapeRoute = ToolsBackslashEscapeRouteImport.update({
  id: '/backslash-escape',
  path: '/backslash-escape',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsAsciiArtRoute = ToolsAsciiArtRouteImport.update({
  id: '/ascii-art',
  path: '/ascii-art',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/ascii-art': typeof ToolsAsciiArtRoute
  '/tools/backslash-escape': typeof ToolsBackslashEscapeRoute
  '/tools/base-conversion': typeof ToolsBaseConversionRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/base64-image': typeof ToolsBase64ImageRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/cipher': typeof ToolsCipherRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/cron-builder': typeof ToolsCronBuilderRoute
  '/tools/cron-parser': typeof ToolsCronParserRoute
  '/tools/css-minifier': typeof ToolsCssMinifierRoute
  '/tools/csv-json': typeof ToolsCsvJsonRoute
  '/tools/data-uri': typeof ToolsDataUriRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/diff-checker': typeof ToolsDiffCheckerRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/html-entity': typeof ToolsHtmlEntityRoute
  '/tools/html-formatter': typeof ToolsHtmlFormatterRoute
  '/tools/http-status': typeof ToolsHttpStatusRoute
  '/tools/image-to-base64': typeof ToolsImageToBase64Route
  '/tools/ip-subnet': typeof ToolsIpSubnetRoute
  '/tools/json-diff': typeof ToolsJsonDiffRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/json-to-typescript': typeof ToolsJsonToTypescriptRoute
  '/tools/json-validator': typeof ToolsJsonValidatorRoute
  '/tools/json-yaml': typeof ToolsJsonYamlRoute
  '/tools/jwt-decoder': typeof ToolsJwtDecoderRoute
  '/tools/jwt-generator': typeof ToolsJwtGeneratorRoute
  '/tools/lorem-ipsum': typeof ToolsLoremIpsumRoute
  '/tools/markdown-preview': typeof ToolsMarkdownPreviewRoute
  '/tools/mock-data': typeof ToolsMockDataRoute
  '/tools/morse-code': typeof ToolsMorseCodeRoute
  '/tools/number-base': typeof ToolsNumberBaseRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/qr-code': typeof ToolsQrCodeRoute
  '/tools/qr-scanner': typeof ToolsQrScannerRoute
  '/tools/random-data': typeof ToolsRandomDataRoute
  '/tools/regex-tester': typeof ToolsRegexTesterRoute
  '/tools/slug-generator': typeof ToolsSlugGeneratorRoute
  '/tools/sql-formatter': typeof ToolsSqlFormatterRoute
  '/tools/string-counter': typeof ToolsStringCounterRoute
  '/tools/text-tools': typeof ToolsTextToolsRoute
  '/tools/timestamp': typeof ToolsTimestampRoute
  '/tools/totp': typeof ToolsTotpRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/tools/url-encode': typeof ToolsUrlEncodeRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/user-agent-parser': typeof ToolsUserAgentParserRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/tools/validator': typeof ToolsValidatorRoute
  '/tools/xml-json': typeof ToolsXmlJsonRoute
  '/tools/yaml-validator': typeof ToolsYamlValidatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/ascii-art': typeof ToolsAsciiArtRoute
  '/tools/backslash-escape': typeof ToolsBackslashEscapeRoute
  '/tools/base-conversion': typeof ToolsBaseConversionRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/base64-image': typeof ToolsBase64ImageRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/cipher': typeof ToolsCipherRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/cron-builder': typeof ToolsCronBuilderRoute
  '/tools/cron-parser': typeof ToolsCronParserRoute
  '/tools/css-minifier': typeof ToolsCssMinifierRoute
  '/tools/csv-json': typeof ToolsCsvJsonRoute
  '/tools/data-uri': typeof ToolsDataUriRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/diff-checker': typeof ToolsDiffCheckerRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/html-entity': typeof ToolsHtmlEntityRoute
  '/tools/html-formatter': typeof ToolsHtmlFormatterRoute
  '/tools/http-status': typeof ToolsHttpStatusRoute
  '/tools/image-to-base64': typeof ToolsImageToBase64Route
  '/tools/ip-subnet': typeof ToolsIpSubnetRoute
  '/tools/json-diff': typeof ToolsJsonDiffRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/json-to-typescript': typeof ToolsJsonToTypescriptRoute
  '/tools/json-validator': typeof ToolsJsonValidatorRoute
  '/tools/json-yaml': typeof ToolsJsonYamlRoute
  '/tools/jwt-decoder': typeof ToolsJwtDecoderRoute
  '/tools/jwt-generator': typeof ToolsJwtGeneratorRoute
  '/tools/lorem-ipsum': typeof ToolsLoremIpsumRoute
  '/tools/markdown-preview': typeof ToolsMarkdownPreviewRoute
  '/tools/mock-data': typeof ToolsMockDataRoute
  '/tools/morse-code': typeof ToolsMorseCodeRoute
  '/tools/number-base': typeof ToolsNumberBaseRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/qr-code': typeof ToolsQrCodeRoute
  '/tools/qr-scanner': typeof ToolsQrScannerRoute
  '/tools/random-data': typeof ToolsRandomDataRoute
  '/tools/regex-tester': typeof ToolsRegexTesterRoute
  '/tools/slug-generator': typeof ToolsSlugGeneratorRoute
  '/tools/sql-formatter': typeof ToolsSqlFormatterRoute
  '/tools/string-counter': typeof ToolsStringCounterRoute
  '/tools/text-tools': typeof ToolsTextToolsRoute
  '/tools/timestamp': typeof ToolsTimestampRoute
  '/tools/totp': typeof ToolsTotpRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/tools/url-encode': typeof ToolsUrlEncodeRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/user-agent-parser': typeof ToolsUserAgentParserRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/tools/validator': typeof ToolsValidatorRoute
  '/tools/xml-json': typeof ToolsXmlJsonRoute
  '/tools/yaml-validator': typeof ToolsYamlValidatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/ascii-art': typeof ToolsAsciiArtRoute
  '/tools/backslash-escape': typeof ToolsBackslashEscapeRoute
  '/tools/base-conversion': typeof ToolsBaseConversionRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/base64-image': typeof ToolsBase64ImageRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/cipher': typeof ToolsCipherRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/cron-builder': typeof ToolsCronBuilderRoute
  '/tools/cron-parser': typeof ToolsCronParserRoute
  '/tools/css-minifier': typeof ToolsCssMinifierRoute
  '/tools/csv-json': typeof ToolsCsvJsonRoute
  '/tools/data-uri': typeof ToolsDataUriRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/diff-checker': typeof ToolsDiffCheckerRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/html-entity': typeof ToolsHtmlEntityRoute
  '/tools/html-formatter': typeof ToolsHtmlFormatterRoute
  '/tools/http-status': typeof ToolsHttpStatusRoute
  '/tools/image-to-base64': typeof ToolsImageToBase64Route
  '/tools/ip-subnet': typeof ToolsIpSubnetRoute
  '/tools/json-diff': typeof ToolsJsonDiffRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/json-to-typescript': typeof ToolsJsonToTypescriptRoute
  '/tools/json-validator': typeof ToolsJsonValidatorRoute
  '/tools/json-yaml': typeof ToolsJsonYamlRoute
  '/tools/jwt-decoder': typeof ToolsJwtDecoderRoute
  '/tools/jwt-generator': typeof ToolsJwtGeneratorRoute
  '/tools/lorem-ipsum': typeof ToolsLoremIpsumRoute
  '/tools/markdown-preview': typeof ToolsMarkdownPreviewRoute
  '/tools/mock-data': typeof ToolsMockDataRoute
  '/tools/morse-code': typeof ToolsMorseCodeRoute
  '/tools/number-base': typeof ToolsNumberBaseRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/qr-code': typeof ToolsQrCodeRoute
  '/tools/qr-scanner': typeof ToolsQrScannerRoute
  '/tools/random-data': typeof ToolsRandomDataRoute
  '/tools/regex-tester': typeof ToolsRegexTesterRoute
  '/tools/slug-generator': typeof ToolsSlugGeneratorRoute
  '/tools/sql-formatter': typeof ToolsSqlFormatterRoute
  '/tools/string-counter': typeof ToolsStringCounterRoute
  '/tools/text-tools': typeof ToolsTextToolsRoute
  '/tools/timestamp': typeof ToolsTimestampRoute
  '/tools/totp': typeof ToolsTotpRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/tools/url-encode': typeof ToolsUrlEncodeRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/user-agent-parser': typeof ToolsUserAgentParserRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/tools/validator': typeof ToolsValidatorRoute
  '/tools/xml-json': typeof ToolsXmlJsonRoute
  '/tools/yaml-validator': typeof ToolsYamlValidatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools'
    | '/tools/ascii-art'
    | '/tools/backslash-escape'
    | '/tools/base-conversion'
    | '/tools/base64'
    | '/tools/base64-image'
    | '/tools/case-converter'
    | '/tools/cipher'
    | '/tools/color-converter'
    | '/tools/color-palette'
    | '/tools/cron-builder'
    | '/tools/cron-parser'
    | '/tools/css-minifier'
    | '/tools/csv-json'
    | '/tools/data-uri'
    | '/tools/diff'
    | '/tools/diff-checker'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/html-entity'
    | '/tools/html-formatter'
    | '/tools/http-status'
    | '/tools/image-to-base64'
    | '/tools/ip-subnet'
    | '/tools/json-diff'
    | '/tools/json-formatter'
    | '/tools/json-to-typescript'
    | '/tools/json-validator'
    | '/tools/json-yaml'
    | '/tools/jwt-decoder'
    | '/tools/jwt-generator'
    | '/tools/lorem-ipsum'
    | '/tools/markdown-preview'
    | '/tools/mock-data'
    | '/tools/morse-code'
    | '/tools/number-base'
    | '/tools/password-generator'
    | '/tools/qr-code'
    | '/tools/qr-scanner'
    | '/tools/random-data'
    | '/tools/regex-tester'
    | '/tools/slug-generator'
    | '/tools/sql-formatter'
    | '/tools/string-counter'
    | '/tools/text-tools'
    | '/tools/timestamp'
    | '/tools/totp'
    | '/tools/unit-converter'
    | '/tools/url-encode'
    | '/tools/url-parser'
    | '/tools/user-agent-parser'
    | '/tools/uuid'
    | '/tools/validator'
    | '/tools/xml-json'
    | '/tools/yaml-validator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools'
    | '/tools/ascii-art'
    | '/tools/backslash-escape'
    | '/tools/base-conversion'
    | '/tools/base64'
    | '/tools/base64-image'
    | '/tools/case-converter'
    | '/tools/cipher'
    | '/tools/color-converter'
    | '/tools/color-palette'
    | '/tools/cron-builder'
    | '/tools/cron-parser'
    | '/tools/css-minifier'
    | '/tools/csv-json'
    | '/tools/data-uri'
    | '/tools/diff'
    | '/tools/diff-checker'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/html-entity'
    | '/tools/html-formatter'
    | '/tools/http-status'
    | '/tools/image-to-base64'
    | '/tools/ip-subnet'
    | '/tools/json-diff'
    | '/tools/json-formatter'
    | '/tools/json-to-typescript'
    | '/tools/json-validator'
    | '/tools/json-yaml'
    | '/tools/jwt-decoder'
    | '/tools/jwt-generator'
    | '/tools/lorem-ipsum'
    | '/tools/markdown-preview'
    | '/tools/mock-data'
    | '/tools/morse-code'
    | '/tools/number-base'
    | '/tools/password-generator'
    | '/tools/qr-code'
    | '/tools/qr-scanner'
    | '/tools/random-data'
    | '/tools/regex-tester'
    | '/tools/slug-generator'
    | '/tools/sql-formatter'
    | '/tools/string-counter'
    | '/tools/text-tools'
    | '/tools/timestamp'
    | '/tools/totp'
    | '/tools/unit-converter'
    | '/tools/url-encode'
    | '/tools/url-parser'
    | '/tools/user-agent-parser'
    | '/tools/uuid'
    | '/tools/validator'
    | '/tools/xml-json'
    | '/tools/yaml-validator'
  id:
    | '__root__'
    | '/'
    | '/tools'
    | '/tools/ascii-art'
    | '/tools/backslash-escape'
    | '/tools/base-conversion'
    | '/tools/base64'
    | '/tools/base64-image'
    | '/tools/case-converter'
    | '/tools/cipher'
    | '/tools/color-converter'
    | '/tools/color-palette'
    | '/tools/cron-builder'
    | '/tools/cron-parser'
    | '/tools/css-minifier'
    | '/tools/csv-json'
    | '/tools/data-uri'
    | '/tools/diff'
    | '/tools/diff-checker'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/html-entity'
    | '/tools/html-formatter'
    | '/tools/http-status'
    | '/tools/image-to-base64'
    | '/tools/ip-subnet'
    | '/tools/json-diff'
    | '/tools/json-formatter'
    | '/tools/json-to-typescript'
    | '/tools/json-validator'
    | '/tools/json-yaml'
    | '/tools/jwt-decoder'
    | '/tools/jwt-generator'
    | '/tools/lorem-ipsum'
    | '/tools/markdown-preview'
    | '/tools/mock-data'
    | '/tools/morse-code'
    | '/tools/number-base'
    | '/tools/password-generator'
    | '/tools/qr-code'
    | '/tools/qr-scanner'
    | '/tools/random-data'
    | '/tools/regex-tester'
    | '/tools/slug-generator'
    | '/tools/sql-formatter'
    | '/tools/string-counter'
    | '/tools/text-tools'
    | '/tools/timestamp'
    | '/tools/totp'
    | '/tools/unit-converter'
    | '/tools/url-encode'
    | '/tools/url-parser'
    | '/tools/user-agent-parser'
    | '/tools/uuid'
    | '/tools/validator'
    | '/tools/xml-json'
    | '/tools/yaml-validator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/yaml-validator': {
      id: '/tools/yaml-validator'
      path: '/yaml-validator'
      fullPath: '/tools/yaml-validator'
      preLoaderRoute: typeof ToolsYamlValidatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/xml-json': {
      id: '/tools/xml-json'
      path: '/xml-json'
      fullPath: '/tools/xml-json'
      preLoaderRoute: typeof ToolsXmlJsonRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/validator': {
      id: '/tools/validator'
      path: '/validator'
      fullPath: '/tools/validator'
      preLoaderRoute: typeof ToolsValidatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/uuid': {
      id: '/tools/uuid'
      path: '/uuid'
      fullPath: '/tools/uuid'
      preLoaderRoute: typeof ToolsUuidRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/user-agent-parser': {
      id: '/tools/user-agent-parser'
      path: '/user-agent-parser'
      fullPath: '/tools/user-agent-parser'
      preLoaderRoute: typeof ToolsUserAgentParserRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/url-parser': {
      id: '/tools/url-parser'
      path: '/url-parser'
      fullPath: '/tools/url-parser'
      preLoaderRoute: typeof ToolsUrlParserRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/url-encode': {
      id: '/tools/url-encode'
      path: '/url-encode'
      fullPath: '/tools/url-encode'
      preLoaderRoute: typeof ToolsUrlEncodeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/unit-converter': {
      id: '/tools/unit-converter'
      path: '/unit-converter'
      fullPath: '/tools/unit-converter'
      preLoaderRoute: typeof ToolsUnitConverterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/totp': {
      id: '/tools/totp'
      path: '/totp'
      fullPath: '/tools/totp'
      preLoaderRoute: typeof ToolsTotpRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/timestamp': {
      id: '/tools/timestamp'
      path: '/timestamp'
      fullPath: '/tools/timestamp'
      preLoaderRoute: typeof ToolsTimestampRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/text-tools': {
      id: '/tools/text-tools'
      path: '/text-tools'
      fullPath: '/tools/text-tools'
      preLoaderRoute: typeof ToolsTextToolsRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/string-counter': {
      id: '/tools/string-counter'
      path: '/string-counter'
      fullPath: '/tools/string-counter'
      preLoaderRoute: typeof ToolsStringCounterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/sql-formatter': {
      id: '/tools/sql-formatter'
      path: '/sql-formatter'
      fullPath: '/tools/sql-formatter'
      preLoaderRoute: typeof ToolsSqlFormatterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/slug-generator': {
      id: '/tools/slug-generator'
      path: '/slug-generator'
      fullPath: '/tools/slug-generator'
      preLoaderRoute: typeof ToolsSlugGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/regex-tester': {
      id: '/tools/regex-tester'
      path: '/regex-tester'
      fullPath: '/tools/regex-tester'
      preLoaderRoute: typeof ToolsRegexTesterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/random-data': {
      id: '/tools/random-data'
      path: '/random-data'
      fullPath: '/tools/random-data'
      preLoaderRoute: typeof ToolsRandomDataRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/qr-scanner': {
      id: '/tools/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/tools/qr-scanner'
      preLoaderRoute: typeof ToolsQrScannerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/qr-code': {
      id: '/tools/qr-code'
      path: '/qr-code'
      fullPath: '/tools/qr-code'
      preLoaderRoute: typeof ToolsQrCodeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/password-generator': {
      id: '/tools/password-generator'
      path: '/password-generator'
      fullPath: '/tools/password-generator'
      preLoaderRoute: typeof ToolsPasswordGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/number-base': {
      id: '/tools/number-base'
      path: '/number-base'
      fullPath: '/tools/number-base'
      preLoaderRoute: typeof ToolsNumberBaseRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/morse-code': {
      id: '/tools/morse-code'
      path: '/morse-code'
      fullPath: '/tools/morse-code'
      preLoaderRoute: typeof ToolsMorseCodeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/mock-data': {
      id: '/tools/mock-data'
      path: '/mock-data'
      fullPath: '/tools/mock-data'
      preLoaderRoute: typeof ToolsMockDataRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/markdown-preview': {
      id: '/tools/markdown-preview'
      path: '/markdown-preview'
      fullPath: '/tools/markdown-preview'
      preLoaderRoute: typeof ToolsMarkdownPreviewRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/lorem-ipsum': {
      id: '/tools/lorem-ipsum'
      path: '/lorem-ipsum'
      fullPath: '/tools/lorem-ipsum'
      preLoaderRoute: typeof ToolsLoremIpsumRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/jwt-generator': {
      id: '/tools/jwt-generator'
      path: '/jwt-generator'
      fullPath: '/tools/jwt-generator'
      preLoaderRoute: typeof ToolsJwtGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/jwt-decoder': {
      id: '/tools/jwt-decoder'
      path: '/jwt-decoder'
      fullPath: '/tools/jwt-decoder'
      preLoaderRoute: typeof ToolsJwtDecoderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/json-yaml': {
      id: '/tools/json-yaml'
      path: '/json-yaml'
      fullPath: '/tools/json-yaml'
      preLoaderRoute: typeof ToolsJsonYamlRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/json-validator': {
      id: '/tools/json-validator'
      path: '/json-validator'
      fullPath: '/tools/json-validator'
      preLoaderRoute: typeof ToolsJsonValidatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/json-to-typescript': {
      id: '/tools/json-to-typescript'
      path: '/json-to-typescript'
      fullPath: '/tools/json-to-typescript'
      preLoaderRoute: typeof ToolsJsonToTypescriptRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/json-formatter': {
      id: '/tools/json-formatter'
      path: '/json-formatter'
      fullPath: '/tools/json-formatter'
      preLoaderRoute: typeof ToolsJsonFormatterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/json-diff': {
      id: '/tools/json-diff'
      path: '/json-diff'
      fullPath: '/tools/json-diff'
      preLoaderRoute: typeof ToolsJsonDiffRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ip-subnet': {
      id: '/tools/ip-subnet'
      path: '/ip-subnet'
      fullPath: '/tools/ip-subnet'
      preLoaderRoute: typeof ToolsIpSubnetRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/image-to-base64': {
      id: '/tools/image-to-base64'
      path: '/image-to-base64'
      fullPath: '/tools/image-to-base64'
      preLoaderRoute: typeof ToolsImageToBase64RouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/http-status': {
      id: '/tools/http-status'
      path: '/http-status'
      fullPath: '/tools/http-status'
      preLoaderRoute: typeof ToolsHttpStatusRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/html-formatter': {
      id: '/tools/html-formatter'
      path: '/html-formatter'
      fullPath: '/tools/html-formatter'
      preLoaderRoute: typeof ToolsHtmlFormatterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/html-entity': {
      id: '/tools/html-entity'
      path: '/html-entity'
      fullPath: '/tools/html-entity'
      preLoaderRoute: typeof ToolsHtmlEntityRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/hmac': {
      id: '/tools/hmac'
      path: '/hmac'
      fullPath: '/tools/hmac'
      preLoaderRoute: typeof ToolsHmacRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/hash': {
      id: '/tools/hash'
      path: '/hash'
      fullPath: '/tools/hash'
      preLoaderRoute: typeof ToolsHashRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/diff-checker': {
      id: '/tools/diff-checker'
      path: '/diff-checker'
      fullPath: '/tools/diff-checker'
      preLoaderRoute: typeof ToolsDiffCheckerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/diff': {
      id: '/tools/diff'
      path: '/diff'
      fullPath: '/tools/diff'
      preLoaderRoute: typeof ToolsDiffRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/data-uri': {
      id: '/tools/data-uri'
      path: '/data-uri'
      fullPath: '/tools/data-uri'
      preLoaderRoute: typeof ToolsDataUriRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/csv-json': {
      id: '/tools/csv-json'
      path: '/csv-json'
      fullPath: '/tools/csv-json'
      preLoaderRoute: typeof ToolsCsvJsonRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/css-minifier': {
      id: '/tools/css-minifier'
      path: '/css-minifier'
      fullPath: '/tools/css-minifier'
      preLoaderRoute: typeof ToolsCssMinifierRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/cron-parser': {
      id: '/tools/cron-parser'
      path: '/cron-parser'
      fullPath: '/tools/cron-parser'
      preLoaderRoute: typeof ToolsCronParserRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/cron-builder': {
      id: '/tools/cron-builder'
      path: '/cron-builder'
      fullPath: '/tools/cron-builder'
      preLoaderRoute: typeof ToolsCronBuilderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/color-palette': {
      id: '/tools/color-palette'
      path: '/color-palette'
      fullPath: '/tools/color-palette'
      preLoaderRoute: typeof ToolsColorPaletteRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/color-converter': {
      id: '/tools/color-converter'
      path: '/color-converter'
      fullPath: '/tools/color-converter'
      preLoaderRoute: typeof ToolsColorConverterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/cipher': {
      id: '/tools/cipher'
      path: '/cipher'
      fullPath: '/tools/cipher'
      preLoaderRoute: typeof ToolsCipherRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/case-converter': {
      id: '/tools/case-converter'
      path: '/case-converter'
      fullPath: '/tools/case-converter'
      preLoaderRoute: typeof ToolsCaseConverterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/base64-image': {
      id: '/tools/base64-image'
      path: '/base64-image'
      fullPath: '/tools/base64-image'
      preLoaderRoute: typeof ToolsBase64ImageRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/base-conversion': {
      id: '/tools/base-conversion'
      path: '/base-conversion'
      fullPath: '/tools/base-conversion'
      preLoaderRoute: typeof ToolsBaseConversionRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/backslash-escape': {
      id: '/tools/backslash-escape'
      path: '/backslash-escape'
      fullPath: '/tools/backslash-escape'
      preLoaderRoute: typeof ToolsBackslashEscapeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ascii-art': {
      id: '/tools/ascii-art'
      path: '/ascii-art'
      fullPath: '/tools/ascii-art'
      preLoaderRoute: typeof ToolsAsciiArtRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsAsciiArtRoute: typeof ToolsAsciiArtRoute
  ToolsBackslashEscapeRoute: typeof ToolsBackslashEscapeRoute
  ToolsBaseConversionRoute: typeof ToolsBaseConversionRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsBase64ImageRoute: typeof ToolsBase64ImageRoute
  ToolsCaseConverterRoute: typeof ToolsCaseConverterRoute
  ToolsCipherRoute: typeof ToolsCipherRoute
  ToolsColorConverterRoute: typeof ToolsColorConverterRoute
  ToolsColorPaletteRoute: typeof ToolsColorPaletteRoute
  ToolsCronBuilderRoute: typeof ToolsCronBuilderRoute
  ToolsCronParserRoute: typeof ToolsCronParserRoute
  ToolsCssMinifierRoute: typeof ToolsCssMinifierRoute
  ToolsCsvJsonRoute: typeof ToolsCsvJsonRoute
  ToolsDataUriRoute: typeof ToolsDataUriRoute
  ToolsDiffRoute: typeof ToolsDiffRoute
  ToolsDiffCheckerRoute: typeof ToolsDiffCheckerRoute
  ToolsHashRoute: typeof ToolsHashRoute
  ToolsHmacRoute: typeof ToolsHmacRoute
  ToolsHtmlEntityRoute: typeof ToolsHtmlEntityRoute
  ToolsHtmlFormatterRoute: typeof ToolsHtmlFormatterRoute
  ToolsHttpStatusRoute: typeof ToolsHttpStatusRoute
  ToolsImageToBase64Route: typeof ToolsImageToBase64Route
  ToolsIpSubnetRoute: typeof ToolsIpSubnetRoute
  ToolsJsonDiffRoute: typeof ToolsJsonDiffRoute
  ToolsJsonFormatterRoute: typeof ToolsJsonFormatterRoute
  ToolsJsonToTypescriptRoute: typeof ToolsJsonToTypescriptRoute
  ToolsJsonValidatorRoute: typeof ToolsJsonValidatorRoute
  ToolsJsonYamlRoute: typeof ToolsJsonYamlRoute
  ToolsJwtDecoderRoute: typeof ToolsJwtDecoderRoute
  ToolsJwtGeneratorRoute: typeof ToolsJwtGeneratorRoute
  ToolsLoremIpsumRoute: typeof ToolsLoremIpsumRoute
  ToolsMarkdownPreviewRoute: typeof ToolsMarkdownPreviewRoute
  ToolsMockDataRoute: typeof ToolsMockDataRoute
  ToolsMorseCodeRoute: typeof ToolsMorseCodeRoute
  ToolsNumberBaseRoute: typeof ToolsNumberBaseRoute
  ToolsPasswordGeneratorRoute: typeof ToolsPasswordGeneratorRoute
  ToolsQrCodeRoute: typeof ToolsQrCodeRoute
  ToolsQrScannerRoute: typeof ToolsQrScannerRoute
  ToolsRandomDataRoute: typeof ToolsRandomDataRoute
  ToolsRegexTesterRoute: typeof ToolsRegexTesterRoute
  ToolsSlugGeneratorRoute: typeof ToolsSlugGeneratorRoute
  ToolsSqlFormatterRoute: typeof ToolsSqlFormatterRoute
  ToolsStringCounterRoute: typeof ToolsStringCounterRoute
  ToolsTextToolsRoute: typeof ToolsTextToolsRoute
  ToolsTimestampRoute: typeof ToolsTimestampRoute
  ToolsTotpRoute: typeof ToolsTotpRoute
  ToolsUnitConverterRoute: typeof ToolsUnitConverterRoute
  ToolsUrlEncodeRoute: typeof ToolsUrlEncodeRoute
  ToolsUrlParserRoute: typeof ToolsUrlParserRoute
  ToolsUserAgentParserRoute: typeof ToolsUserAgentParserRoute
  ToolsUuidRoute: typeof ToolsUuidRoute
  ToolsValidatorRoute: typeof ToolsValidatorRoute
  ToolsXmlJsonRoute: typeof ToolsXmlJsonRoute
  ToolsYamlValidatorRoute: typeof ToolsYamlValidatorRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsAsciiArtRoute: ToolsAsciiArtRoute,
  ToolsBackslashEscapeRoute: ToolsBackslashEscapeRoute,
  ToolsBaseConversionRoute: ToolsBaseConversionRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsBase64ImageRoute: ToolsBase64ImageRoute,
  ToolsCaseConverterRoute: ToolsCaseConverterRoute,
  ToolsCipherRoute: ToolsCipherRoute,
  ToolsColorConverterRoute: ToolsColorConverterRoute,
  ToolsColorPaletteRoute: ToolsColorPaletteRoute,
  ToolsCronBuilderRoute: ToolsCronBuilderRoute,
  ToolsCronParserRoute: ToolsCronParserRoute,
  ToolsCssMinifierRoute: ToolsCssMinifierRoute,
  ToolsCsvJsonRoute: ToolsCsvJsonRoute,
  ToolsDataUriRoute: ToolsDataUriRoute,
  ToolsDiffRoute: ToolsDiffRoute,
  ToolsDiffCheckerRoute: ToolsDiffCheckerRoute,
  ToolsHashRoute: ToolsHashRoute,
  ToolsHmacRoute: ToolsHmacRoute,
  ToolsHtmlEntityRoute: ToolsHtmlEntityRoute,
  ToolsHtmlFormatterRoute: ToolsHtmlFormatterRoute,
  ToolsHttpStatusRoute: ToolsHttpStatusRoute,
  ToolsImageToBase64Route: ToolsImageToBase64Route,
  ToolsIpSubnetRoute: ToolsIpSubnetRoute,
  ToolsJsonDiffRoute: ToolsJsonDiffRoute,
  ToolsJsonFormatterRoute: ToolsJsonFormatterRoute,
  ToolsJsonToTypescriptRoute: ToolsJsonToTypescriptRoute,
  ToolsJsonValidatorRoute: ToolsJsonValidatorRoute,
  ToolsJsonYamlRoute: ToolsJsonYamlRoute,
  ToolsJwtDecoderRoute: ToolsJwtDecoderRoute,
  ToolsJwtGeneratorRoute: ToolsJwtGeneratorRoute,
  ToolsLoremIpsumRoute: ToolsLoremIpsumRoute,
  ToolsMarkdownPreviewRoute: ToolsMarkdownPreviewRoute,
  ToolsMockDataRoute: ToolsMockDataRoute,
  ToolsMorseCodeRoute: ToolsMorseCodeRoute,
  ToolsNumberBaseRoute: ToolsNumberBaseRoute,
  ToolsPasswordGeneratorRoute: ToolsPasswordGeneratorRoute,
  ToolsQrCodeRoute: ToolsQrCodeRoute,
  ToolsQrScannerRoute: ToolsQrScannerRoute,
  ToolsRandomDataRoute: ToolsRandomDataRoute,
  ToolsRegexTesterRoute: ToolsRegexTesterRoute,
  ToolsSlugGeneratorRoute: ToolsSlugGeneratorRoute,
  ToolsSqlFormatterRoute: ToolsSqlFormatterRoute,
  ToolsStringCounterRoute: ToolsStringCounterRoute,
  ToolsTextToolsRoute: ToolsTextToolsRoute,
  ToolsTimestampRoute: ToolsTimestampRoute,
  ToolsTotpRoute: ToolsTotpRoute,
  ToolsUnitConverterRoute: ToolsUnitConverterRoute,
  ToolsUrlEncodeRoute: ToolsUrlEncodeRoute,
  ToolsUrlParserRoute: ToolsUrlParserRoute,
  ToolsUserAgentParserRoute: ToolsUserAgentParserRoute,
  ToolsUuidRoute: ToolsUuidRoute,
  ToolsValidatorRoute: ToolsValidatorRoute,
  ToolsXmlJsonRoute: ToolsXmlJsonRoute,
  ToolsYamlValidatorRoute: ToolsYamlValidatorRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
