import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Server, Copy, Check, Download, ExternalLink } from "lucide-react";

export default function HtaccessGeneratorPage() {
  const [options, setOptions] = useState({
    forceHttps: false,
    forceWww: false,
    removeWww: false,
    customRedirect: false,
    blockIps: false,
    preventHotlinking: false,
    enableGzip: false,
    enableCaching: false,
    customErrorPages: false,
    disableDirectoryBrowsing: false,
    protectFiles: false,
  });

  const [customRedirectFrom, setCustomRedirectFrom] = useState("");
  const [customRedirectTo, setCustomRedirectTo] = useState("");
  const [blockedIps, setBlockedIps] = useState("");
  const [domain, setDomain] = useState("example.com");
  const [error404, setError404] = useState("/404.html");
  const [error500, setError500] = useState("/500.html");
  const [protectedFiles, setProtectedFiles] = useState(".htaccess\n.htpasswd\nwp-config.php");

  const [output, setOutput] = useState("");
  const [copied, setCopied] = useState(false);

  const generateHtaccess = () => {
    let htaccess = "# Generated by DevTools .htaccess Generator\n\n";

    // Force HTTPS
    if (options.forceHttps) {
      htaccess += "# Force HTTPS\n";
      htaccess += "RewriteEngine On\n";
      htaccess += "RewriteCond %{HTTPS} off\n";
      htaccess += "RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n";
    }

    // Force WWW
    if (options.forceWww) {
      htaccess += "# Force WWW\n";
      htaccess += "RewriteEngine On\n";
      htaccess += "RewriteCond %{HTTP_HOST} !^www\\. [NC]\n";
      htaccess += "RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n";
    }

    // Remove WWW
    if (options.removeWww) {
      htaccess += "# Remove WWW\n";
      htaccess += "RewriteEngine On\n";
      htaccess += "RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]\n";
      htaccess += "RewriteRule ^(.*)$ https://%1%{REQUEST_URI} [L,R=301]\n\n";
    }

    // Custom redirect
    if (options.customRedirect && customRedirectFrom && customRedirectTo) {
      htaccess += "# Custom Redirect\n";
      htaccess += `Redirect 301 ${customRedirectFrom} ${customRedirectTo}\n\n`;
    }

    // Block IPs
    if (options.blockIps && blockedIps) {
      htaccess += "# Block Specific IP Addresses\n";
      htaccess += "<Limit GET POST>\n";
      htaccess += "order allow,deny\n";
      blockedIps.split("\n").forEach((ip) => {
        if (ip.trim()) {
          htaccess += `deny from ${ip.trim()}\n`;
        }
      });
      htaccess += "allow from all\n";
      htaccess += "</Limit>\n\n";
    }

    // Prevent hotlinking
    if (options.preventHotlinking) {
      htaccess += "# Prevent Image Hotlinking\n";
      htaccess += "RewriteEngine On\n";
      htaccess += "RewriteCond %{HTTP_REFERER} !^$\n";
      htaccess += `RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${domain} [NC]\n`;
      htaccess += "RewriteRule \\.(jpg|jpeg|png|gif|svg|webp)$ - [F,NC]\n\n";
    }

    // Enable Gzip compression
    if (options.enableGzip) {
      htaccess += "# Enable Gzip Compression\n";
      htaccess += "<IfModule mod_deflate.c>\n";
      htaccess += "  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json\n";
      htaccess += "</IfModule>\n\n";
    }

    // Browser caching
    if (options.enableCaching) {
      htaccess += "# Browser Caching\n";
      htaccess += "<IfModule mod_expires.c>\n";
      htaccess += "  ExpiresActive On\n";
      htaccess += "  ExpiresByType image/jpg \"access plus 1 year\"\n";
      htaccess += "  ExpiresByType image/jpeg \"access plus 1 year\"\n";
      htaccess += "  ExpiresByType image/gif \"access plus 1 year\"\n";
      htaccess += "  ExpiresByType image/png \"access plus 1 year\"\n";
      htaccess += "  ExpiresByType image/svg+xml \"access plus 1 year\"\n";
      htaccess += "  ExpiresByType text/css \"access plus 1 month\"\n";
      htaccess += "  ExpiresByType application/javascript \"access plus 1 month\"\n";
      htaccess += "  ExpiresByType text/html \"access plus 0 seconds\"\n";
      htaccess += "</IfModule>\n\n";
    }

    // Custom error pages
    if (options.customErrorPages) {
      htaccess += "# Custom Error Pages\n";
      htaccess += `ErrorDocument 404 ${error404}\n`;
      htaccess += `ErrorDocument 500 ${error500}\n\n`;
    }

    // Disable directory browsing
    if (options.disableDirectoryBrowsing) {
      htaccess += "# Disable Directory Browsing\n";
      htaccess += "Options -Indexes\n\n";
    }

    // Protect files
    if (options.protectFiles && protectedFiles) {
      htaccess += "# Protect Sensitive Files\n";
      protectedFiles.split("\n").forEach((file) => {
        if (file.trim()) {
          htaccess += `<Files ${file.trim()}>\n`;
          htaccess += "  Order allow,deny\n";
          htaccess += "  Deny from all\n";
          htaccess += "</Files>\n";
        }
      });
      htaccess += "\n";
    }

    setOutput(htaccess);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = ".htaccess";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const loadTemplate = (template: string) => {
    switch (template) {
      case "basic":
        setOptions({
          ...options,
          forceHttps: true,
          disableDirectoryBrowsing: true,
        });
        break;
      case "wordpress":
        setOptions({
          ...options,
          forceHttps: true,
          disableDirectoryBrowsing: true,
          protectFiles: true,
        });
        setProtectedFiles(".htaccess\n.htpasswd\nwp-config.php\nerror_log");
        break;
      case "performance":
        setOptions({
          ...options,
          enableGzip: true,
          enableCaching: true,
        });
        break;
      case "security":
        setOptions({
          ...options,
          forceHttps: true,
          disableDirectoryBrowsing: true,
          protectFiles: true,
          preventHotlinking: true,
        });
        break;
    }
  };

  return (
    <div className="container mx-auto p-6 max-w-6xl">
      <div className="mb-6">
        <h1 className="text-3xl font-bold mb-2">.htaccess Generator</h1>
        <p className="text-muted-foreground">
          Generate Apache .htaccess configuration files with common settings
        </p>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Templates</CardTitle>
              <CardDescription>
                Quick start with common configurations
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" size="sm" onClick={() => loadTemplate("basic")}>
              Basic Security
            </Button>
            <Button variant="outline" size="sm" onClick={() => loadTemplate("wordpress")}>
              WordPress
            </Button>
            <Button variant="outline" size="sm" onClick={() => loadTemplate("performance")}>
              Performance
            </Button>
            <Button variant="outline" size="sm" onClick={() => loadTemplate("security")}>
              Security Hardening
            </Button>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Server className="h-5 w-5" />
              General Options
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-start space-x-2">
              <Checkbox
                id="forceHttps"
                checked={options.forceHttps}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, forceHttps: checked as boolean })
                }
              />
              <Label htmlFor="forceHttps" className="cursor-pointer leading-tight">
                Force HTTPS (redirect HTTP to HTTPS)
              </Label>
            </div>

            <div className="flex items-start space-x-2">
              <Checkbox
                id="forceWww"
                checked={options.forceWww}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, forceWww: checked as boolean })
                }
              />
              <Label htmlFor="forceWww" className="cursor-pointer leading-tight">
                Force WWW prefix
              </Label>
            </div>

            <div className="flex items-start space-x-2">
              <Checkbox
                id="removeWww"
                checked={options.removeWww}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, removeWww: checked as boolean })
                }
              />
              <Label htmlFor="removeWww" className="cursor-pointer leading-tight">
                Remove WWW prefix
              </Label>
            </div>

            <div className="flex items-start space-x-2">
              <Checkbox
                id="disableDirectoryBrowsing"
                checked={options.disableDirectoryBrowsing}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, disableDirectoryBrowsing: checked as boolean })
                }
              />
              <Label htmlFor="disableDirectoryBrowsing" className="cursor-pointer leading-tight">
                Disable directory browsing
              </Label>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Performance & Security</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-start space-x-2">
              <Checkbox
                id="enableGzip"
                checked={options.enableGzip}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, enableGzip: checked as boolean })
                }
              />
              <Label htmlFor="enableGzip" className="cursor-pointer leading-tight">
                Enable Gzip compression
              </Label>
            </div>

            <div className="flex items-start space-x-2">
              <Checkbox
                id="enableCaching"
                checked={options.enableCaching}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, enableCaching: checked as boolean })
                }
              />
              <Label htmlFor="enableCaching" className="cursor-pointer leading-tight">
                Enable browser caching
              </Label>
            </div>

            <div className="flex items-start space-x-2">
              <Checkbox
                id="preventHotlinking"
                checked={options.preventHotlinking}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, preventHotlinking: checked as boolean })
                }
              />
              <Label htmlFor="preventHotlinking" className="cursor-pointer leading-tight">
                Prevent image hotlinking
              </Label>
            </div>

            {options.preventHotlinking && (
              <div className="ml-6 space-y-2">
                <Label htmlFor="domain">Your Domain</Label>
                <Input
                  id="domain"
                  value={domain}
                  onChange={(e) => setDomain(e.target.value)}
                  placeholder="example.com"
                />
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Additional Options</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-4">
            <div className="flex items-start space-x-2">
              <Checkbox
                id="customRedirect"
                checked={options.customRedirect}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, customRedirect: checked as boolean })
                }
              />
              <Label htmlFor="customRedirect" className="cursor-pointer">
                Custom 301 Redirect
              </Label>
            </div>

            {options.customRedirect && (
              <div className="ml-6 grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="redirectFrom">From</Label>
                  <Input
                    id="redirectFrom"
                    value={customRedirectFrom}
                    onChange={(e) => setCustomRedirectFrom(e.target.value)}
                    placeholder="/old-page"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="redirectTo">To</Label>
                  <Input
                    id="redirectTo"
                    value={customRedirectTo}
                    onChange={(e) => setCustomRedirectTo(e.target.value)}
                    placeholder="https://example.com/new-page"
                  />
                </div>
              </div>
            )}

            <div className="flex items-start space-x-2">
              <Checkbox
                id="blockIps"
                checked={options.blockIps}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, blockIps: checked as boolean })
                }
              />
              <Label htmlFor="blockIps" className="cursor-pointer">
                Block IP Addresses
              </Label>
            </div>

            {options.blockIps && (
              <div className="ml-6 space-y-2">
                <Label htmlFor="blockedIps">IP Addresses (one per line)</Label>
                <Textarea
                  id="blockedIps"
                  value={blockedIps}
                  onChange={(e) => setBlockedIps(e.target.value)}
                  placeholder="192.168.1.1&#10;10.0.0.1"
                  className="font-mono text-sm"
                  rows={3}
                />
              </div>
            )}

            <div className="flex items-start space-x-2">
              <Checkbox
                id="customErrorPages"
                checked={options.customErrorPages}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, customErrorPages: checked as boolean })
                }
              />
              <Label htmlFor="customErrorPages" className="cursor-pointer">
                Custom Error Pages
              </Label>
            </div>

            {options.customErrorPages && (
              <div className="ml-6 grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="error404">404 Page</Label>
                  <Input
                    id="error404"
                    value={error404}
                    onChange={(e) => setError404(e.target.value)}
                    placeholder="/404.html"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="error500">500 Page</Label>
                  <Input
                    id="error500"
                    value={error500}
                    onChange={(e) => setError500(e.target.value)}
                    placeholder="/500.html"
                  />
                </div>
              </div>
            )}

            <div className="flex items-start space-x-2">
              <Checkbox
                id="protectFiles"
                checked={options.protectFiles}
                onCheckedChange={(checked) =>
                  setOptions({ ...options, protectFiles: checked as boolean })
                }
              />
              <Label htmlFor="protectFiles" className="cursor-pointer">
                Protect Sensitive Files
              </Label>
            </div>

            {options.protectFiles && (
              <div className="ml-6 space-y-2">
                <Label htmlFor="protectedFiles">Files to protect (one per line)</Label>
                <Textarea
                  id="protectedFiles"
                  value={protectedFiles}
                  onChange={(e) => setProtectedFiles(e.target.value)}
                  placeholder=".htaccess&#10;wp-config.php"
                  className="font-mono text-sm"
                  rows={3}
                />
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      <div className="mb-6">
        <Button onClick={generateHtaccess} size="lg" className="w-full lg:w-auto">
          <Server className="h-4 w-4 mr-2" />
          Generate .htaccess
        </Button>
      </div>

      {output && (
        <Card className="mb-6">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Generated .htaccess</CardTitle>
                <CardDescription>
                  Place this file in the root directory of your website
                </CardDescription>
              </div>
              <div className="flex gap-2">
                <Button variant="ghost" size="sm" onClick={handleCopy}>
                  {copied ? (
                    <>
                      <Check className="h-4 w-4 mr-1" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="h-4 w-4 mr-1" />
                      Copy
                    </>
                  )}
                </Button>
                <Button variant="ghost" size="sm" onClick={handleDownload}>
                  <Download className="h-4 w-4 mr-1" />
                  Download
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <Textarea
              value={output}
              readOnly
              className="font-mono text-xs min-h-[400px] bg-muted"
            />
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>About .htaccess</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
          <p>
            .htaccess is a configuration file for Apache web servers that allows you to
            control how your website behaves without modifying server configuration files.
          </p>
          <p>
            <strong>Important:</strong> Always backup your existing .htaccess file before
            making changes. Incorrect configuration can break your website.
          </p>
          <p>
            <strong>Testing:</strong> After uploading, test all functionality to ensure
            nothing is broken. Some hosting providers may have restrictions on certain
            directives.
          </p>
          <div className="flex items-center gap-2 pt-2">
            <ExternalLink className="h-4 w-4" />
            <a
              href="https://httpd.apache.org/docs/current/howto/htaccess.html"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-primary"
            >
              Learn more about .htaccess
            </a>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
