APPLY_FIXES: all
FILTER_REGEX_EXCLUDE: (pnpm-lock.yaml)
JSON_V8R_FILTER_REGEX_INCLUDE: (.devcontainer)

DISABLE_LINTERS:
  - CSS_STYLELINT
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - TYPESCRIPT_STANDARD
  - JSON_JSONLINT
  - YAML_YAMLLINT
  - REPOSITORY_TRIVY
  - YAML_V8R

SHOW_ELAPSED_TIME: true
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false

FILEIO_REPORTER: false
